CLUSTER-API-205: Initialize the 'flag' library to remove error message from glog (#206)
Prior to this change, every line of logging had the following error message prefixing the actual log:

  ERROR: logging before flag.Parse

This is because glog has a hard dependency on the flag package. This 'hack' serves to make glog happy.