UPSTREAM: <759>: openshift: config: Adjust to new version of kustomize.
The newest versions of kustomize block the use of relative paths, so
the "kustomize build config/default/" command now fails with the
following error message:

Error: rawResources failed to read Resources: Load from path ../crds/cluster_v1alpha1_cluster.yaml failed: security; file '../crds/cluster_v1alpha1_cluster.yaml' is not in or below '.../github.com/kubernetes-sigs/cluster-api/config/default'

This patch resolves this by moving kustomization.yaml down a
directory, so that all files it points to are in the same or
sub-directories of its location.

This was merged into upstream cluster-api via:
https://github.com/kubernetes-sigs/cluster-api/pull/759

Signed-off-by: Russell Bryant <rbryant@redhat.com>