minikube: use --profile instead of --p
It was reported that "minikube start" fails:
  minikube start --bootstrapper=kubeadm --p=clusterapi
  Error: unknown flag: --p

From "minikube start --help":
  -p, --profile string

Use --profile in minikube.go as --p does not work.
The alternative is -p.